version: '2'
services:
    jhipsterelastictest-app:
        image: jhipsterelastictest
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterelastictest-mysql:3306/jhipsterelastictest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://jhipsterelastictest-elasticsearch:9200
        ports:
            - 8080:8080
    jhipsterelastictest-mysql:
        extends:
            file: mysql.yml
            service: jhipsterelastictest-mysql
    jhipsterelastictest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterelastictest-elasticsearch
